require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/ticket_types", type: :request do
  let(:event) { Event.create!(name: 'Event name') }

  # This should return the minimal set of attributes required to create a valid
  # TicketType. As you add validations to TicketType, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {
      name: 'Ticket Name',
      event: event,
    }
  }

  let(:invalid_attributes) {
    {
      name: '',
      event: event,
    }
  }

  describe "GET /new" do
    it "renders a successful response" do
      get new_event_ticket_type_url(event)
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      ticket_type = TicketType.create! valid_attributes
      get edit_event_ticket_type_url(event, ticket_type)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TicketType" do
        expect {
          post event_ticket_types_url(event), params: { ticket_type: valid_attributes }
        }.to change(TicketType, :count).by(1)
      end

      it "redirects to the created ticket_type" do
        post event_ticket_types_url(event), params: { ticket_type: valid_attributes }
        expect(response).to redirect_to(event_url(event))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TicketType" do
        expect {
          post event_ticket_types_url(event), params: { ticket_type: invalid_attributes }
        }.to change(TicketType, :count).by(0)
      end


      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post event_ticket_types_url(event), params: { ticket_type: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end

    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested ticket_type" do
        ticket_type = TicketType.create! valid_attributes
        patch event_ticket_type_url(event, ticket_type), params: { ticket_type: new_attributes }
        ticket_type.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the ticket_type" do
        ticket_type = TicketType.create! valid_attributes
        patch event_ticket_type_url(event, ticket_type), params: { ticket_type: new_attributes }
        ticket_type.reload
        expect(response).to redirect_to(event_url(event))
      end
    end

    context "with invalid parameters" do

      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        ticket_type = TicketType.create! valid_attributes
        patch event_ticket_type_url(event, ticket_type), params: { ticket_type: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end

    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested ticket_type" do
      ticket_type = TicketType.create! valid_attributes
      expect {
        delete event_ticket_type_url(event, ticket_type)
      }.to change(TicketType, :count).by(-1)
    end

    it "redirects to the ticket_types list" do
      ticket_type = TicketType.create! valid_attributes
      delete event_ticket_type_url(event, ticket_type)
      expect(response).to redirect_to(event_url(event))
    end
  end
end
